-- 코드를 입력하세요 , i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS, 

SELECT i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS, ROUND(AVG(r.REVIEW_SCORE),2) as SCORE
FROM REST_INFO i
INNER JOIN REST_REVIEW r
ON i.REST_ID = r.REST_ID
WHERE i.ADDRESS LIKE '서울%'
GROUP BY i.REST_ID
ORDER BY SCORE desc, i.FAVORITES desc;

# SELECT REST_ID, REST_NAME,  FOOD_TYPE,  FAVORITES,  ADDRESS, 
#         round(avg(REVIEW_SCORE),2)  SCORE
# FROM REST_INFO i JOIN REST_REVIEW r USING (REST_ID)
# WHERE ADDRESS LIKE '서울%'
# GROUP BY REST_ID
# order by SCORE desc, FAVORITES desc